Add an Arduino example with documentation.
blues/notecard-env-var-manager pull request #5
Opened 2023-04-21 18:29 UTC by haydenroche5

2023-04-21 18:30 UTC, haydenroche5 commented on src/NotecardEnvVarManager.h
> -    NEVM_WAITING = -2,
Not needed after removing the latent cache stuff.

2023-04-23 13:59 UTC, zfields requested changes
There is some [other boilerplate](https://github.com/blues/note-arduino/blob/master/examples/Example5_UsingTemplates/Example5_UsingTemplates.ino#L34) we typically add to let folks choose between TX/RX and I2C, but I don't think it's strictly necessary.

In my comments, I updated this with the minimum boilerplate that fits what you have already put forth.

2023-04-23 13:59 UTC, zfields commented on examples/arduino/arduino.ino
> +#include <Wire.h>
It is not necessary to include `Wire.h`.
```suggestion
```

2023-04-23 13:59 UTC, zfields commented on examples/arduino/arduino.ino
> +        strncpy(cache->valueB, val, sizeof(cache->valueA));
```suggestion
        strncpy(cache->valueB, val, sizeof(cache->valueB));
```

2023-04-23 13:59 UTC, zfields commented on examples/arduino/arduino.ino
> +        strncpy(cache->valueC, val, sizeof(cache->valueA));
```suggestion
        strncpy(cache->valueC, val, sizeof(cache->valueC));
```

2023-04-23 13:59 UTC, zfields commented on examples/arduino/arduino.ino
> +    Wire.begin();
Unnecessary to call Wire.begin();
```suggestion
```

2023-04-23 13:59 UTC, zfields commented on examples/arduino/arduino.ino
> +    // Set up debug output via serial connection.
This is how we handle awaiting `Serial` in the other examples...

```suggestion
    // If you open Arduino's serial terminal window, you'll be able to watch
    // JSON objects being transferred to and from the Notecard for each request.
    Serial.begin(115200);
    const size_t serial_timeout_ms = 3000;
    for (const size_t start_ms = millis(); !Serial && (millis() - start_ms) < serial_timeout_ms;)
        ;
```

2023-04-23 13:59 UTC, zfields commented on examples/arduino/arduino.ino
> +    uint32_t currentMs = NoteGetMs();
`NoteGetMs()` is an abstraction that we typically use internally for libraries that may not be written to the Arduino API. Personally, I would use `millis()` here, but this is harmless.

```suggestion
    uint32_t currentMs = millis();
```

2023-04-23 13:59 UTC, zfields commented on examples/arduino/arduino.ino
> +        return;
The example has failed at this point. If you `return` you move onto `loop()`.

```suggestion
        while(1);
```

2023-04-23 13:59 UTC, zfields commented on examples/arduino/arduino.ino
> +        return;
The example has failed at this point. If you `return` you move onto `loop()`.

```suggestion
        while(1);
```

2023-04-23 13:59 UTC, zfields commented on examples/arduino/arduino.ino
> +        return;
The example has failed at this point. If you `return` you move onto `loop()`.

```suggestion
        while(1);
```

2023-04-25 16:12 UTC, zfields commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add an Arduino example for the NotecardEnvVarManager](https://trello.com/c/7d2eXyvm/102-add-an-arduino-example-for-the-notecardenvvarmanager)

2023-05-13 19:12 UTC, zfields approved these changes

2023-05-15 18:37 UTC, merged